### ISSUE TITLE
Apply di_ prefix to components

### ISSUE THREAD

**Issue by afawcett** [afawcett/force-di#12]
Eventually, we will create a 2GP namespaced package version of this lib (with the di_ prefix removed from its public facing API) as an additional means to consume this lib for those that prefer that. Meanwhile, we will assume early adopters will want to use the library as-is and thus to scope its components using the prefix approach. This also works well for ISV's and Enterprise devs, who may not want to depend on the 2GP namespaced unlocked package, but still, want the segregation a prefix gives in their broader code base.

**Comment by ImJohnMDaniel** [comment]
Re-opened in order to tweak the prefix to be lowercase, per discussion with @afawcett and @douglascayers
