### ISSUE TITLE
di_Binding__mdt.BIndingObject__c data type does not support all SObject types

### ISSUE THREAD

**Issue by ImJohnMDaniel** [afawcett/force-di#33]
@afawcett and @douglascayers -- FYI, last week we came across a use case that showed that the MetadataRelationship to EntityDefinition data type for the di_Binding__mdt.BindingObject__c field does not support all SObject types available.  Most notably is that it does not support the User SObject, but it also does not support several other SObjects including BusinessHours, Event, FiscalYearSettings, Group, Holiday, and several others.

This is most definitely a limitation with the MetadataRelationship EntityDefinition data type and not the Force-DI code.  The question becomes how to accommodate these other SObjects from the di_Binding__mdt record.

I can think of two solutions. 
A) add a new field on di__Binding__mdt called BindingObjectAlternate__c which would be a TEXT(255) data type.  We could allow the admin to use this field to specify an SObject API name not covered by BindingObject__c.  We would adjust the code that loads the bindings to use the BindingObject__c field first or the BindingObjectAlternate__c second for the API Binding name.  We could also put a validation rule in place to throw an error if both fields were populated.

B) we change the data type of BindingObject__c to be simply TEXT(255) and thus remove the limitation all together.

What are your thoughts on this subject?

**Comment by ImJohnMDaniel** [comment]
FYI @stohn777

**Comment by douglascayers** [comment]
My concern with introducing a second field is that our code now needs to keep up with both fields, which isn't ideal. We'd need to introduce (I think) an abstraction layer for querying and interacting with the binding record so our code can just ask for "the binding object" and the abstraction layer (e.g. wrapper object) would figure out which field was populated and return that value.

If we switch to just the text field then we're guaranteed it'll support any object forever, we never need to revisit this code. The downside is that the UI isn't as sexy out of the box for end-users to just use a picklist to select the object.

I would argue that the downside to switching can be overcome with a simple custom UI that provides a picklist populated by Schema global describe. In this way, we provide the helpful UI to the end-users and we maintain only one field. Meaning, any code changes are always going in a forward movement and not really needing to come back and "undo" or "deprecate" our approach.

Thoughts @afawcett @ImJohnMDaniel @stohn777
